# Generated by Django 3.1.2 on 2022-02-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('sleep_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('deep_period', models.IntegerField(null=True)),
                ('rem_period', models.IntegerField(null=True)),
                ('light_period', models.IntegerField(null=True)),
                ('awake_period', models.IntegerField(null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
