# Generated by Django 3.1.2 on 2022-02-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220212_1658'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(type__in=['SPORT', 'SYMPTOM']), name='$(app_label)s_event_type_valid'),
        ),
    ]
