# Generated by Django 3.1.2 on 2022-02-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='sleep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sleep'),
        ),
    ]
