# Generated by Django 3.1.2 on 2022-02-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220216_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomGroup',
            fields=[
                ('symptom_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_time', models.DateTimeField()),
                ('has_ectopic_beats', models.BooleanField()),
                ('has_dizziness', models.BooleanField()),
                ('has_chest_pain', models.BooleanField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='$(app_label)s_event_type_valid',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('SLEEP', 'Sleep'), ('SYMPTOM_GROUP', 'Symptom Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(type__in=['SLEEP', 'SYMPTOM_GROUP']), name='$(app_label)s_event_type_valid'),
        ),
        migrations.AddField(
            model_name='event',
            name='symptom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.symptomgroup'),
        ),
    ]
