# Generated by Django 3.1.2 on 2022-02-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220216_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('WORKOUT', 'Workout'), ('CARDIO', 'Cardio')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('WORKOUT', 'Workout'), ('CARDIO', 'Cardio')], max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='$(app_label)s_event_type_valid',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('SLEEP', 'Sleep'), ('SYMPTOM_GROUP', 'Symptom Group'), ('SPORT', 'Sport'), ('FOOD', 'Food'), ('ACTIVITY', 'Activity')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(type__in=['SLEEP', 'SYMPTOM_GROUP', 'SPORT', 'FOOD', 'ACTIVITY']), name='$(app_label)s_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='sport',
            constraint=models.CheckConstraint(check=models.Q(type__in=['WORKOUT', 'CARDIO']), name='$(app_label)s_sport_type_valid'),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.recipe'),
        ),
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.activity'),
        ),
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.food'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sport'),
        ),
    ]
