# Generated by Django 3.1.2 on 2022-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20220217_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
