# Generated by Django 3.2.5 on 2022-02-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('WORKOUT', 'Workout'), ('CARDIO', 'Cardio')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('SLEEP', 'Sleep'), ('SYMPTOM_GROUP', 'Symptom Group'), ('SPORT', 'Sport'), ('FOOD', 'Food'), ('ACTIVITY', 'Activity')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.JSONField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('sleep_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('deep_period', models.IntegerField(null=True)),
                ('rem_period', models.IntegerField(null=True)),
                ('light_period', models.IntegerField(null=True)),
                ('awake_period', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('WORKOUT', 'Workout'), ('CARDIO', 'Cardio')], max_length=20, null=True)),
                ('calories', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomGroup',
            fields=[
                ('symptom_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_time', models.DateTimeField()),
                ('has_ectopic_beats', models.BooleanField()),
                ('has_dizziness', models.BooleanField()),
                ('has_chest_pain', models.BooleanField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sport',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['WORKOUT', 'CARDIO'])), name='$(app_label)s_sport_type_valid'),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.recipe'),
        ),
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.activity'),
        ),
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.food'),
        ),
        migrations.AddField(
            model_name='event',
            name='sleep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sleep'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sport'),
        ),
        migrations.AddField(
            model_name='event',
            name='symptom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.symptomgroup'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['SLEEP', 'SYMPTOM_GROUP', 'SPORT', 'FOOD', 'ACTIVITY'])), name='$(app_label)s_event_type_valid'),
        ),
    ]
